import { createBrowserRouter, Navigate } from "react-router-dom";
import Root from "./components/Root";
import Home from "./components/Home";
import Login from "./components/Login";
import SignUp from "./components/SignUp";
import DesignSystem from "./components/DesignSystem";
import FigmaDesignGallery from "./components/FigmaDesignGallery";
import MenuShowcase from "./components/MenuShowcase";
import Insights from "./components/Insights";
import Administration from "./components/Administration";
import CreateSpace from "./components/CreateSpace";
import CreateUnit from "./components/CreateUnit";
import AddUnits from "./components/AddUnits";
import AutoGeneratedUnits from "./components/AutoGeneratedUnits";
import ManualAddUnit from "./components/ManualAddUnit";
import CreatedUnits from "./components/CreatedUnits";
import CreateLease from "./components/CreateLease";
import CreateCustomer from "./components/CreateCustomer";
import CreatePricing from "./components/CreatePricing";
import CreateDocuments from "./components/CreateDocuments";
import ManageSpaces from "./components/ManageSpaces";
import EditSpace from "./components/EditSpace";
import AddFloor from "./components/AddFloor";
import ManageUnits from "./components/ManageUnits";
import ManageUnitsView from "./components/ManageUnitsView";
import EditUnit from "./components/EditUnit";
import EditUnitWrapper from "./components/EditUnitWrapper";
import ManageLeases from "./components/ManageLeases";
import EditLease from "./components/EditLease";
import ManageCustomers from "./components/ManageCustomers";
import EditCustomer from "./components/EditCustomer";
import ManagePricing from "./components/ManagePricing";
import ManageBookings from "./components/ManageBookings";
import ManagePayments from "./components/ManagePayments";
import DocumentGeneration from "./components/DocumentGeneration";
import NotificationCenterPage from "./components/NotificationCenterPage";

export const router = createBrowserRouter([
  { path: "/login", Component: Login },
  { path: "/signup", Component: SignUp },
  {
    path: "/",
    Component: Root,
    children: [
      { index: true, Component: Home },
      { path: "menus", Component: MenuShowcase },
      { path: "design-system", Component: DesignSystem },
      { path: "notifications", Component: NotificationCenterPage },
      { path: "figma-35", Component: FigmaDesignGallery },
      { path: "create", element: <Navigate to="/create/space" replace /> },
      { path: "create/space", Component: CreateSpace },
      { path: "create/units", Component: CreateUnit },
      { 
        path: "create/units/configure", 
        Component: AddUnits,
        // Force remount when navigating with different state
        id: "create-units-configure"
      },
      { path: "create/units/auto-generated", Component: AutoGeneratedUnits },
      { path: "create/units/manual-add", Component: ManualAddUnit },
      { path: "create/created-units", Component: CreatedUnits },
      { path: "create/lease", Component: CreateLease },
      { path: "create/customer", Component: CreateCustomer },
      { path: "create/pricing", Component: CreatePricing },
      { path: "create/documents", Component: CreateDocuments },
      { path: "manage", element: <Navigate to="/manage/spaces" replace /> },
      { path: "manage/spaces", Component: ManageSpaces },
      { path: "manage/edit-space/:spaceId", Component: EditSpace },
      { path: "manage/add-floor/:spaceId", Component: AddFloor },
      { path: "manage/edit-unit/:spaceId/:unitId", Component: EditUnit },
      { path: "manage/edit-unit/:unitId", Component: EditUnitWrapper },
      { path: "manage/units", Component: ManageUnits },
      { path: "manage/units/:spaceId", Component: ManageUnits },
      { path: "manage/units-view", Component: ManageUnitsView },
      { path: "manage/leases", Component: ManageLeases },
      { path: "manage/edit-lease/:leaseId", Component: EditLease },
      { path: "manage/customers", Component: ManageCustomers },
      { path: "manage/edit-customer/:customerId", Component: EditCustomer },
      { path: "manage/pricing", Component: ManagePricing },
      { path: "manage/bookings", Component: ManageBookings },
      { path: "manage/payments", Component: ManagePayments },
      { path: "insights", Component: Insights },
      { path: "administration", Component: Administration },
      { path: "*", element: <Navigate to="/" replace /> },
    ],
  },
]);
